import { access, readFile } from "node:fs/promises";
import { resolve } from "node:path";

const root = resolve(new URL("..", import.meta.url).pathname);
const required = [
  "dist/apps/web/server.mjs",
  "dist/apps/web/server-runtime.mjs",
  "dist/apps/web/public/index.html",
  "dist/apps/web/public/auth.html",
  "dist/apps/web/public/auth.js",
  "dist/apps/web/public/great-hall.html",
  "dist/apps/web/public/great-hall.js",
  "dist/apps/web/public/room.html",
  "dist/apps/web/public/room.js",
  "dist/apps/web/public/keeper.js",
  "dist/apps/web/public/vault.html",
  "dist/apps/web/public/vault.js",
  "dist/apps/web/public/vault.css",
  "dist/apps/web/public/vault-import.js",
  "dist/apps/web/public/vault-import.css",
  "dist/apps/web/public/vault-categories.js",
  "dist/apps/web/public/vault-provenance.js",
  "dist/apps/web/public/vault-details.js",
  "dist/apps/web/public/vault-details.css",
  "dist/apps/web/public/vault-saved-views.js",
  "dist/apps/web/public/vault-saved-views.css",
  "dist/apps/web/public/vault-evidence.js",
  "dist/apps/web/public/vault-evidence.css",
  "dist/apps/web/public/vault-view-modes.js",
  "dist/apps/web/public/vault-view-modes.css",
  "dist/apps/web/public/vault-system-views.js",
  "dist/apps/web/public/vault-system-views.css",
  "dist/apps/web/public/vault-sets.js",
  "dist/apps/web/public/vault-sets.css",
  "dist/apps/web/public/vault-marketplace-readiness.js",
  "dist/apps/web/public/vault-marketplace-readiness.css",
  "dist/apps/web/public/vault-ui-styles.js",
  "dist/apps/web/public/styles.css",
  "dist/apps/web/public/world.css",
  "dist/apps/web/public/assets/keeper.svg",
  "dist/apps/web/public/assets/marketplace.svg",
  "dist/config/runtime.mjs",
  "dist/packages/core/src/health.mjs",
  "dist/packages/observability/src/logger.mjs",
  "dist/packages/identity/src/passwords.mjs",
  "dist/packages/identity/src/tokens.mjs",
  "dist/packages/identity/src/sqlite-store.mjs",
  "dist/packages/identity/src/service.mjs",
  "dist/packages/kings-ai/src/client.mjs",
  "dist/packages/great-hall/src/service.mjs",
  "dist/packages/vault/src/sqlite-store.mjs",
  "dist/packages/vault/src/service.mjs",
  "dist/packages/vault/src/http.mjs",
  "dist/packages/vault/src/ownership.mjs",
  "dist/packages/vault/src/portable.mjs",
  "dist/packages/vault/src/taxonomy.mjs",
  "dist/packages/vault/src/attributes.mjs",
  "dist/packages/vault/src/search.mjs",
  "dist/packages/vault/src/saved-searches.mjs",
  "dist/packages/vault/src/evidence.mjs",
  "dist/packages/vault/src/sets.mjs",
  "dist/packages/vault/src/set-summaries.mjs",
  "dist/packages/vault/src/sets-http.mjs",
  "dist/packages/vault/src/marketplace-readiness.mjs",
  "dist/packages/vault/src/marketplace-readiness-http.mjs",
  "dist/packages/vault/src/intelligence.mjs",
  "dist/build-manifest.json"
];

for (const relative of required) await access(resolve(root, relative));
const manifest = JSON.parse(await readFile(resolve(root, "dist/build-manifest.json"), "utf8"));
if (manifest.phase !== "IMP-005-VAULT-PHASE-1") throw new Error("Unexpected build phase in manifest.");
if (manifest.entrypoint !== "apps/web/server-runtime.mjs") throw new Error("Production manifest does not point to the composed Kingdom runtime.");
console.log("Production artifact verification passed for IMP-005 Royal Vault Phase 1 output, including portable intake, provenance, category intelligence, extended search, saved Vault views, protected evidence documents, explicit collection-set completion with aggregate progress summaries and checklist UI, transparent Marketplace handoff readiness and preparation UI, Grid/List/Binder/Gallery presentation assets, authoritative recent/favorite/incomplete-set/Marketplace-ready/duplicate system views, live enrichment UI assets, and bounded Royal Curator context.");
